config/routes.rb
Rails.application.routes.draw do
    # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

    # Defines the root path route ("/")
    # root "articles#index"

    root 'tasks#index'

    get 'signup', to: 'users#new'
    post 'signup', to: 'users#create'

    get 'login', to: 'sessions#new'
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy'

    resources :users, only: [] do
        resources :tasks, only: :index
    end
    resources :tasks, only: %i[create update]

    namespace :api do
        get 'login', to: 'login#show'
        resources :tasks, only: %i[index create update]
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    has_many :tasks
    has_secure_password
    has_secure_token :api_token

    validates :name, presence: true
    validates :account_id, presence: true, uniqueness: true
end

app/controllers/api/login_controller.rb
class Api::LoginController < ApplicationController
    def show
        @user = User.find_by(account_id: params[:account_id])
        if @user&.authenticate(params[:password])
            render status: :ok, json: { api_token: @user.api_token }
        else
            render status: :unauthorized, json: {}
        end
    end
end

app/controllers/api/tasks_controller.rb
class Api::TasksController < ApplicationController
    skip_forgery_protection

    before_action :authenticate_by_token

    def index
        @tasks = @user.tasks.where(created_at: Time.zone.today.all_day)
        render json: @tasks.map { |task| { id: task.id, name: task.name, finished: task.finished } } 
    end

    def create
        task = Task.create(task_params.merge(user: @user))
        render json: { id: task.id, name: task.name, finished: task.finished }, status: :created
    end

    def update
        task = Task.find(params[:id])
        (task.user == @user) ? task.update(task_params) : render(status: :unauthorized)
    end

    private

    def authenticate_by_token
        @user = User.find_by(api_token: params[:api_token])
        render status: :unauthorized, json: 'Invalid API token' if @user.blank?
    end

    def task_params
        params.require(:task).permit(:name, :finished)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new; 
    end
  
    def create
        user = User.find_by(account_id: params[:session][:account_id])
        if user&.authenticate(params[:session][:password])
            login user
            redirect_to root_path
        else
            flash.now[:alert] = 'アカウントID、またはパスワードが間違っています。'
            render :new
        end
    end

    def destroy
        logout
        redirect_to login_path
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    before_action :login_required
    before_action :set_user

    def index
        @tasks = @user.tasks.where(created_at: Time.zone.today.all_day)
    end

    def create
        @task = Task.create(task_params.merge(user: current_user))
        redirect_to Rails.application.routes.recognize_path(request.referer)
    end

    def update
        task = Task.find(params[:id])
        redirect_to login_path if task.user != current_user
        task.update(task_params)
    end

    private

    def login_required
        redirect_to login_path unless logged_in?
    end

    def set_user
        @user = (params[:user_id].present?? User.find(params[:user_id]) : current_user)
    end

    def task_params
        params.require(:task).permit(:name, :finished)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        render :new unless @user.save
    end

    private
    
    def user_params
        params.require(:user).permit(:name, :account_id, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def login(user)
        session[:user_id] = user.id
    end

    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end

    def logged_in?
        current_user.present?
    end

    def logout
        session.delete(:user_id)
        @current_user = nil
    end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails7Todo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-ujs/1.2.2/rails.js"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/index.html.erb
<p><%= @user.name %></p>

<% if @user == current_user %>
    <%= form_with model: Task.new, local: true do |f| %>
        <%= f.text_field :name, required: true %>
        <%= f.submit '作成' %>
    <% end %>
<% end %>

<ul>
    <% @tasks.each do |task| %>
        <li>
        <%= check_box_tag "finished#{task.id}", true, task.finished, data: { id: task.id }, disabled: (@user != current_user) %>
        <%= label_tag "finished#{task.id}", task.name %>
        </li>
    <% end %>
</ul>

<%= link_to 'ログアウト', logout_path, method: :delete %>

<% if @user == current_user %>
    <script>
        $(document).ready(function(){
            $('#task_name').focus();
        });

        $('input[type="checkbox"]').change(function() {
          $.ajax('/tasks/' + $(this).data('id'),
            {
              type: 'patch',
              data: {
                task: {
                  finished: $(this).prop('checked')
                }
              },
              dataType: 'json'
            }
          )
        });
    </script>
<% end %>

<style>
    li { list-style: none; }

    :checked + label {
        color: gray;
        text-decoration: line-through;
    }
</style>

app/views/users/create.html.erb
<p>ご登録ありがとうございます。</p>
<p><%= link_to 'ログインページ', login_path %>からログインしてご利用を開始してください。</p>

app/views/users/new.html.erb
<%= form_with model: @user, url: signup_path, local: true do |f| %>
    <% if @user.errors.any? %>
        <ul>
            <% @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
        </ul>
    <% end %>

    <p>
        <%= f.label :name, 'お名前' %>
        <%= f.text_field :name, required: true %>
    </p>
  
    <p>
        <%= f.label :account_id, 'アカウントID' %>
        <%= f.text_field :account_id, required: true %>
    </p>
  
    <p>
        <%= f.label :password, 'パスワード' %>
        <%= f.password_field :password, required: true %>
    </p>
  
    <p>
        <%= f.label :password_confirmation, 'パスワード(確認)' %>
        <%= f.password_field :password_confirmation, required: true %>
    </p>
  
    <p><%= f.submit '送信' %></p>
<% end %>

<%= link_to 'ログインはこちら', login_path %>